config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'projects#index'
  get 'main/index'
  resources :projects, only: [:create, :update, :destroy] do
    resources :tasks, only: [:show, :create, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task

  has_attached_file :attachment, override_file_permissions: false

  # validates_attachment :attachment, content_type: {
  #   content_type: %w(application/pdf)
  # }
  do_not_validate_attachment_file_type :attachment
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: true
  validates :priority, presence: true

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github]
  
  has_many :projects

  def self.from_omniauth(auth)

    user = where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = find_by(email: auth.info.email)
      unless user
        #byebug
        user = create(provider: auth.provider, uid: auth.uid, 
                      email: auth.info.email, password: Devise.friendly_token[0, 20])
      end
    end

    user

    # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    #   byebug
    #   user.email = auth.info.email
    #   user.password = Devise.friendly_token[0, 20]
    # end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create!(comment_params)
    render_comments
  end

  def destroy
    Comment.destroy params[:id]
    render_comments
  end

  private

  def comment_params
    c = params.require(:comment).permit(:txt, :attachment)
    t = params.permit(:task_id)
    c.merge t
  end

  def render_comments
    @task = Task.find(params[:task_id])
    @comment = Comment.new

    respond_to do |format|
      format.js { render 'tasks/show' }
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    omniauth_sign_in :facebook
  end


  def google_oauth2
    omniauth_sign_in :google
  end

  def github
    omniauth_sign_in :github
  end

  private

  def omniauth_sign_in(authorizer = nil)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: authorizer.to_s.capitalize) if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def create
    @new_prj = Project.create(name: "New Project", user_id:  current_user.id)

    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js {}
    end
  end

  # TODO: Check user and id and render error page if needed
  def update
    @project = Project.find(params[:id])
    @project.update(name: (params[:project][:name]))
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    Project.delete(params[:id])
    @id = params[:id]
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js {}
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :update, :destroy]

  # TODO: check if project_id is valid
  def create
    task = Task.new
    task.start_date = Time.now
    task.name = task_params[:name] # params[:task][:name]
    task.project_id = params[:project_id]
    task.priority = task.project.tasks.count
    task.save!

    render_project(task.project_id)
  end

  def show
    @comment = Comment.new
  end

  # TODO: Fix Rubocop wornings
  # Order is like a priority at present
  def update
    @task.name =        task_params[:name]        if task_params[:name]
    @task.status =      task_params[:status]      if task_params[:status]
    @task.priority =    task_params[:order]       if task_params[:order]
    @task.note =        task_params[:note]        if task_params[:note]
    @task.start_date =  task_params[:start_date]  if task_params[:start_date]
    @task.due_date =    task_params[:due_date]    if task_params[:due_date]
    @task.attachment =  task_params[:attachment]  if task_params[:attachment]
    @task.save! if project_valid?
    prioritize(@task) if task_params[:order]

    render_project @task.project_id
  end

  # TODO: check if task is valid
  def destroy
    @task.destroy! if project_valid?
    render_project @task.project_id
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    {
      name:       params[:task][:name],
      status:     params[:task][:status],
      order:      params[:task][:order],
      note:       params[:task][:note],
      start_date: params[:task][:start_date],
      due_date:   params[:task][:due_date],
      attachment: params[:task][:attachment]
    }
  end

  def project_valid?
    @task.project_id == params[:project_id].to_i
  end

  def render_project(id)
    @project = Project.find(id)
    respond_to do |format|
      #format.html { render 'projects/update' }
      format.js { render 'projects/update' }
    end
  end

  def prioritize(task)
    prio = 0
    task.project.tasks.order(priority: :asc).each do |t|
      next if t.id == task.id || t.status == 'completed'
      prio += 1 if prio == task.priority
      t.priority = prio
      t.save!
      prio += 1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def date_time_convert(datetime)
    return nil if datetime.nil?
    return datetime.to_date.to_s if datetime.hour == 0 && datetime.min == 0
    datetime.to_s
  end

  def attachment_class(comment)
    case comment.attachment_content_type
    when "text/plain"
      "text_plain"
    when "application/pdf"
      "application_pdf"
    when "application/pdf"
      "application_pdf"
    when "application/zip"
      "application_zip"
    when "application/msword",
         "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      "application_msword"
    when "application/vnd.ms-excel"
      "application_vnd_ms_excel"
    else "unknown_type"
    end
  end
end

app/views/comments/create.js.erb
alert('Ok');

app/views/layouts/_footer.html.erb
<div id="footer">
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<p>


&copyRubyGarage</p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <ul>
    <div class="to_left">
      <li> <%= link_to "About", main_index_path %> </li>
      <% if user_signed_in? %>
        <li> <%= link_to "My tasks", root_path %> </li>
      <%end%>
    </div>

    <div class="to_right">
      <% if user_signed_in? %>
        <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li> <%= link_to "Register", new_user_registration_path %> </li>
        <li> <%= link_to "Sign in", new_user_session_path %> </li>
      <% end %>
    </div>
  </ul>
</div>

<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true,
                             async: Rails.env.production? %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<%= render 'layouts/header' %>

<div id="main_page">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/main/index.html.erb
<div id="about_page">

<h1>Task manager</h1>
<p>
I'm a person who passionate about my own productivity. I want to manage my tasks and projects more effectively. I need a simple tool that supports me in controlling my task-flow
</p>
<br>
<ul><strong>Functional requirements</strong>
  <li>I want to be able to create/update/delete projects </li>
  <li>I want to be able to add tasks to my project </li>
  <li>I want to be able to update/delete tasks </li>
  <li>I want to be able to prioritize tasks into a project</li>
  <li>I want to be able to choose deadline for my task</li>
  <li>I want to be able to mark a task as 'done'</li>
</ul>
<br>
<ul><strong>Technical requirements</strong>
  <li>It should be a WEB application </li>
  <li>For the client side must be used: HTML, CSS (any libs as Twitter Bootstrap, Blueprint ...), JavaScript (any libs as jQuery, Prototype ...) </li>
  <li>For a server side any language as Ruby, PHP, Python, JavaScript, C#, Java ...</li>
  <li>It should have a client side and server side validation</li>
  <li>It should look like on screens (see attached file ‘rg_test_task_grid.png’).</li>
 </ul>
<br>
<ul><strong>Additional functionality </strong>
  <li>It should work like one page WEB application and should use AJAX technology, load and submit data without reloading a page.</li>
  <li>It should have user authentication solution and a user should only have access to their own projects and tasks.</li>
  <li>It should have automated tests for the all functionality</li>
</ul>
<br>
<br>
<h1>SQL task</h1>
<ul><strong>Given tables: </strong>
  <li>tasks (id, name, status, project_id) </li>
  <li>projects (id, name)</li>
</ul>

<ol><strong>Write the queries for:</strong>
<li>get all statuses, not repeating, alphabetically ordered</li>
<li>get the count of all tasks in each project, order by tasks count descending</li>
<li>get the count of all tasks in each project, order by projects names</li>
<li>get the tasks for all projects having the name beginning with “N” letter</li>
<li>get the list of all projects containing the ‘a’ letter in the middle of the name, and show the tasks count near each project. Mention that there can exist projects without tasks and tasks with project_id=NULL</li>
<li>get the list of tasks with duplicate names. Order alphabetically</li>
<li>get the list of tasks having several exact matches of both name and status, from the project ‘Garage’. Order by matches count</li>
<li>get the list of project names having more than 10 tasks in status ‘completed’. Order by project_id</li>
</ol>

</div>

app/views/projects/_project.html.erb
<table class="project_table" id=<%= "project_" + project.id.to_s%>>

<!--********************** TODO list header *********************************-->
  <thead>
    <tr>
      <td><%= image_tag "note.png", alt: "note"%></td>
      <td class="prj_name">
        <%= form_for(project, remote: true) do |f| %>
        <%= content_tag :p, "#{project.name}"  %>
        <%= f.text_field :name, class: "prj_name_text"%>
        <% end %>
      </td>
      <td></td>
      <td><%= button_to "", "#", class: "prj_edit_btn" %></td>
      <td><%= button_to "", project_path(project.id), class: "delete_btn", 
                      method: :delete, data: { confirm: "Are you sure?" }, 
                      remote: true%></td>
    </tr>
  </thead>

<!--************************ Add Task row ***********************************-->
  <tr class="new_task_row">
    <td><%= button_to "", "#", class: "plus_task_btn" %></td>

    <td> 
      <%= form_for([project, Task.new], remote: true, 
                    html: {class: "new_task_form"}) do |f| %>
        <%= f.text_field :name, value: "Start typing here to create a task…" %>
      <% end %>
    </td>
    <td colspan="3"><%= button_to "Add task", "#", class: "add_task_btn" %></td>
  </tr>

<!--************************* Tasks rows ************************************-->
  <tbody class="sortable">
  <% project.tasks.order(priority: :asc).each do |t| %>
    <% if t.status != 'completed' %>
      <tr class="task_row">

<!--  Checkbox -->
        <td> 
          <%= form_for( [project, t], remote: true, 
                        html: {class: 'task_order'}) do |f| %>
              <%= f.hidden_field :order, value: 0 %>
          <% end %>
          <%= form_for([project, t], remote: true) do |f| %>
            <%= f.check_box 'status', {class: 'task_checkbox'}, "completed" %>
          <% end %>
        </td>

<!--  Taskname -->
        <td> 
          <%= form_for([project, t], remote: true, 
                        html: {class: "task_form"}) do |f| %>
            <%= f.text_field :name, disabled: true %>
          <% end %>
        </td>

<!--  Buttons -->
        <td>
          <%= button_to '', '#', class: 'prio_task_btn task_edit_btn', 
                          method: :edit%></td>
        <td><%= button_to '', [project, t], 
                          class: 'edit_task_btn task_edit_btn', 
                          method: :get, remote: true%>
        </td>
        <td><%= button_to '', [project, t], 
                          class: 'delete_task_btn task_edit_btn', 
                          method: :delete, remote: true, 
                          data: { confirm: 'Are you sure?' }%></td>
      </tr>

    <% end %>
  <% end %>
  </tbody>
</table>

app/views/projects/create.js.erb
$('#project_next').replaceWith(
  " <%= j render partial: 'project', locals: {project: @new_prj} %>" 
  + "<div id=\"project_next\"></div>");

app/views/projects/destroy.js.erb
$("<%= '#project_' +  @id.to_s%>").remove();

app/views/projects/index.html.erb
<h1>SIMPLE TODO LISTS</h1>
<h2>FROM RUBY GARAGE</h2>

<div id="project">
  <% @projects.each do |p| %>
    <%= render partial: 'project', locals: {project: p}%>
  <% end %>

  <div id="project_next"></div>
</div>

<div id="edit_task_wnd" title="Edit Task"></div>

  <%= button_to "Add TODO List", projects_path, class: "add_prj_btn",
                method: :create, remote: true %>

app/views/projects/new.js.erb
$('#project_next').replaceWith(
  " <%= j render partial: 'project', locals: {project: @new_prj} %>" 
  + "<div id=\"project_next\"></div>");

app/views/projects/update.js.erb
// full path 'projects/project' is used bicause it's calling from task controller
$("<%= '#project_' +  @project.id.to_s%>").html( "<%= j render partial: 'projects/project', locals: {project: @project}%>" );

// FIX: Can it cause async problems?
set_sortable();
set_btn_hover();

app/views/tasks/_task_form.html.erb
  <%= form_for( [@task.project, @task], remote: true) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :note, placeholder: "Note" %>
    <%= label :task, :start_date, "Start date:" %>
    <%= f.text_field :start_date, placeholder: "none", class: "datepicker", 
                     value: date_time_convert(@task.start_date) %>
    <%= label :task, :due_date, "Due date:" %>
    <%= f.text_field :due_date, placeholder: "none", class: "datepicker",
                      value: date_time_convert(@task.due_date) %>
  <% end %>

  <%= form_for [@task.project, @task, @comment], 
                remote: true, 
                authenticity_token: true do |f| %>
    <%= f.text_field :txt, placeholder: "New comment" %>
    <%= f.file_field :attachment, class: "to_right" %>
    <%= label(:comment, :attachment, class: "attachment_btn") {"".html_safe}%>
  <% end %>

<ul>
<% @task.comments.each do |cm| %>
  <li <div class="comments">
    <%= "#{cm.txt}"%>
    <% if cm.attachment %>
    <%# byebug %>
      <%= button_to "", project_task_comment_path( @task.project_id, @task.id, cm.id  ), 
                    class: "delete_btn to_right", method: :delete, remote: true %>
      <%= link_to '',
                  cm.attachment.url,
                  class: "to_right " + attachment_class(cm),
                  title: cm.attachment_file_name,
                  :target => "_blank" %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/tasks/show.js.erb
// Modal window parametres
var wnd_params = {
    modal: true,
    autoOpen: false,
    resizable : false,
    width: 600,
    height: "auto",
    show: { effect: "slideDown", duration: 200 },
    hide: { effect: "slideUp",   duration: 200 }



    // buttons: [ {
    //   text: "Cancel",
    //   click: function() { $( this ).dialog( "close" ); }
    // }, {
    //   text: "Save",
    //   click: function() { 
    //     $(this).find('form').submit(); 
    //     $(this).dialog( "close" );
    //   }
    // }]
  };

// Put all calls into function to avoid async problem
(function() {
  $('#edit_task_wnd').html("<%= j render partial: 'tasks/task_form' %>");
  $('#edit_task_wnd').dialog().dialog(wnd_params);
  $('#edit_task_wnd').dialog('open');
  //$(function() {
    $('.datepicker').datepicker({dateFormat: 'yy-mm-dd'});

    $('.edit_task').change(function() {
      debugger;
      $(this).submit();
    });

  //});
  $('#comment_attachment').change(function() {
    debugger;
    var a = this;
  })
})();